export const AUTHENTICATE_ADMIN = "AUTHENTICATE_ADMIN";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const REQUEST_PROJECT_CATEGORY = 'REQUEST_PROJECT_CATEGORY';
export const SUCCESS_PROJECT_CATEGORY = 'SUCCESS_PROJECTS_CATEGORY';
export const FAILURE_PROJECT_CATEGORY = 'FAILURE_PROJECT_CATEGORY';
