export const AUTHENTICATE_ADMIN = "AUTHENTICATE_ADMIN";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOCALE_SET = 'LOCALE_SET';

// Add categories of the projects action types
export const REQUEST_ADD_PROJECT_CATEGORY = 'REQUEST_ADD_PROJECT_CATEGORY';
export const SUCCESS_ADD_PROJECT_CATEGORY = 'SUCCESS_ADD_PROJECT_CATEGORY';
export const FAILURE_ADD_PROJECT_CATEGORY = 'FAILURE_ADD_PROJECT_CATEGORY';

// Get all categories of the projects action types
export const REQUEST_GET_PROJECT_CATEGORIES = 'REQUEST_GET_PROJECT_CATEGORIES';
export const SUCCESS_GET_PROJECT_CATEGORIES = 'SUCCESS_GET_PROJECT_CATEGORIES';
export const FAILURE_GET_PROJECT_CATEGORIES = 'FAILURE_GET_PROJECT_CATEGORIES';

// Get selected category
export const REQUEST_GET_SELECTED_CATEGORY = 'REQUEST_GET_SELECTED_CATEGORY';
export const SUCCESS_GET_SELECTED_CATEGORY = 'SUCCESS_GET_SELECTED_CATEGORY';
export const FAILURE_GET_SELECTED_CATEGORY = 'FAILURE_GET_SELECTED_CATEGORY';

// Update selected category
export const REQUEST_UPDATE_SELECTED_CATEGORY = 'REQUEST_UPDATE_SELECTED_CATEGORY';
export const SUCCESS_UPDATE_SELECTED_CATEGORY = 'SUCCESS_UPDATE_SELECTED_CATEGORY';
export const FAILURE_UPDATE_SELECTED_CATEGORY = 'FAILURE_UPDATE_SELECTED_CATEGORY';



// Add project action types
export const REQUEST_ADD_PROJECT = 'REQUEST_ADD_PROJECT';
export const SUCCESS_ADD_PROJECT = 'SUCCESS_ADD_PROJECT';
export const FAILURE_ADD_PROJECT = 'FAILURE_ADD_PROJECT';

// Get all projects action types
export const REQUEST_GET_ALL_PROJECTS = 'REQUEST_GET_ALL_PROJECTS'
export const SUCCESS_GET_ALL_PROJECTS = 'SUCCESS_GET_ALL_PROJECTS'
export const FAILURE_GET_ALL_PROJECTS = 'FAILURE_GET_ALL_PROJECTS'

// Get project by category action types
export const REQUEST_GET_PROJECT_BY_CATEGORY = 'REQUEST_GET_PROJECT_BY_CATEGORY'
export const SUCCESS_GET_PROJECT_BY_CATEGORY = 'SUCCESS_GET_PROJECT_BY_CATEGORY'
export const FAILURE_GET_PROJECT_BY_CATEGORY = 'FAILURE_GET_PROJECT_BY_CATEGORY'

// Get project by PROJECT_ID
export const REQUEST_GET_PROJECT_BY_PROJECT_ID = 'REQUEST_GET_PROJECT_BY_PROJECT_ID'
export const SUCCESS_GET_PROJECT_BY_PROJECT_ID = 'SUCCESS_GET_PROJECT_BY_PROJECT_ID'
export const FAILURE_GET_PROJECT_BY_PROJECT_ID = 'FAILURE_GET_PROJECT_BY_PROJECT_ID'

// Add new expertise
export const REQUEST_ADD_EXPERTISE = 'REQUEST_ADD_EXPERTISE'
export const SUCCESS_ADD_EXPERTISE = 'SUCCESS_ADD_EXPERTISE'
export const FAILURE_ADD_EXPERTISE = 'FAILURE_ADD_EXPERTISE'

// Get all expertise 
export const REQUEST_GET_ALL_EXPERTISES = 'REQUEST_GET_ALL_EXPERTISES'
export const SUCCESS_GET_ALL_EXPERTISES = 'SUCCESS_GET_ALL_EXPERTISES'
export const FAILURE_GET_ALL_EXPERTISES = 'FAILURE_GET_ALL_EXPERTISES'

export const REQUEST_DELETE_EXPERTISE = 'REQUEST_DELETE_EXPERTISE'
export const SUCCESS_DELETE_EXPERTISE = 'SUCCESS_DELETE_EXPERTISE'
export const FAILURE_DELETE_EXPERTISE = 'FAILURE_DELETE_EXPERTISE'

// Get expertise by id
export const REQUEST_GET_EXPERTISE_BY_ID = 'REQUEST_GET_EXPERTISE_BY_ID'
export const SUCCESS_GET_EXPERTISE_BY_ID = 'SUCCESS_GET_EXPERTISE_BY_ID'
export const FAILURE_GET_EXPERTISE_BY_ID = 'FAILURE_GET_EXPERTISE_BY_ID'

// Add new team member
export const SUCCESS_ADD_NEW_TEAM_MEMBER = 'SUCCESS_ADD_NEW_TEAM_MEMBER'
export const FAILURE_ADD_NEW_TEAM_MEMBER = 'FAILURE_ADD_NEW_TEAM_MEMBER'

// Get team
export const SUCCESS_GET_TEAM = 'SUCCESS_GET_TEAM'
export const FAILURE_GET_TEAM = 'FAILURE_GET_TEAM'

export const SUCCESS_DELETE_TEAM_MEMBER = 'SUCCESS_DELETE_TEAM_MEMBER'
export const FAILURE_DELETE_TEAM_MEMBER = 'FAILURE_DELETE_TEAM_MEMBER'
