export const AUTHENTICATE_ADMIN = "AUTHENTICATE_ADMIN";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOCALE_SET = 'LOCALE_SET';

// Add categories of the projects action types
export const REQUEST_ADD_PROJECT_CATEGORY = 'REQUEST_ADD_PROJECT_CATEGORY';
export const SUCCESS_ADD_PROJECT_CATEGORY = 'SUCCESS_ADD_PROJECT_CATEGORY';
export const FAILURE_ADD_PROJECT_CATEGORY = 'FAILURE_ADD_PROJECT_CATEGORY';

// Get all categories of the projects action types
export const REQUEST_GET_PROJECT_CATEGORIES = 'REQUEST_GET_PROJECT_CATEGORIES';
export const SUCCESS_GET_PROJECT_CATEGORIES = 'SUCCESS_GET_PROJECT_CATEGORIES';
export const FAILURE_GET_PROJECT_CATEGORIES = 'FAILURE_GET_PROJECT_CATEGORIES';

// Add project action types
export const REQUEST_ADD_PROJECT = 'REQUEST_ADD_PROJECT';
export const SUCCESS_ADD_PROJECT = 'SUCCESS_ADD_PROJECT';
export const FAILURE_ADD_PROJECT = 'FAILURE_ADD_PROJECT';

// Get all projects action types
export const REQUEST_GET_ALL_PROJECTS = 'REQUEST_GET_ALL_PROJECTS'
export const SUCCESS_GET_ALL_PROJECTS = 'SUCCESS_GET_ALL_PROJECTS'
export const FAILURE_GET_ALL_PROJECTS = 'FAILURE_GET_ALL_PROJECTS'
